"""Byte-fidelity regression tests for download endpoints.

These tests compare the web API's TXT and CSV output byte-for-byte against
reference files generated by the desktop application. This is the quality gate
for OUTP-01 (byte-perfect ISS.NET format).

HOW TO ENABLE:
    Place desktop-generated reference files in tests/fixtures/{municipality}/expected/
    and the corresponding XML inputs in tests/fixtures/{municipality}/input/.
    See tests/fixtures/README.md for filename conventions.

CURRENT STATUS:
    All tests are SKIPPED until reference fixture files are provided.
    No test failures will occur with an empty fixtures directory.
"""

from pathlib import Path

import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures"

MUNICIPALITIES = ["goiania", "aparecida", "anapolis", "brasilia"]


def _has_expected_txt(municipality: str) -> bool:
    """Return True if at least one .txt file exists in the expected/ directory."""
    expected_dir = FIXTURE_DIR / municipality / "expected"
    return expected_dir.exists() and any(expected_dir.glob("*.txt"))


def _has_expected_csv(municipality: str) -> bool:
    """Return True if at least one .csv file exists in the expected/ directory."""
    expected_dir = FIXTURE_DIR / municipality / "expected"
    return expected_dir.exists() and any(expected_dir.glob("*.csv"))


def _expected_txt_files(municipality: str) -> list[Path]:
    """Return all .txt reference files for a municipality (may be empty)."""
    expected_dir = FIXTURE_DIR / municipality / "expected"
    if not expected_dir.exists():
        return []
    return list(expected_dir.glob("*.txt"))


def _expected_csv_files(municipality: str) -> list[Path]:
    """Return all .csv reference files for a municipality (may be empty)."""
    expected_dir = FIXTURE_DIR / municipality / "expected"
    if not expected_dir.exists():
        return []
    return list(expected_dir.glob("*.csv"))


# ---------------------------------------------------------------------------
# TXT byte-fidelity tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("municipality", MUNICIPALITIES)
def test_txt_byte_fidelity(municipality: str) -> None:
    """Compare API-generated TXT bytes against desktop-generated reference files.

    SKIPPED when no .txt reference fixtures are present for the municipality.

    TODO (once fixtures arrive):
        1. Parse emp_cod and vigencia from the reference filename
           (convention: {emp_cod}_{vigencia}.txt, e.g. 001_032026.txt).
        2. POST the XML files from input/ to the API:
               POST /jobs  (multipart, emp_cod=..., vigencia=..., files=[...])
        3. Poll GET /jobs/{id}/status until status == "completed".
        4. GET /jobs/{id}/download/txt  →  download_bytes
        5. Assert download_bytes == expected_path.read_bytes()
           (byte-for-byte, catches encoding/line-ending/delimiter regressions)
    """
    if not _has_expected_txt(municipality):
        pytest.skip(f"No reference TXT fixtures for '{municipality}' — add files to "
                    f"tests/fixtures/{municipality}/expected/ to enable this test")

    expected_files = _expected_txt_files(municipality)
    assert len(expected_files) > 0, (
        f"Expected TXT fixtures found but list is empty for '{municipality}'"
    )

    for expected_path in expected_files:
        expected_bytes = expected_path.read_bytes()
        assert len(expected_bytes) > 0, (
            f"Reference fixture is empty: {expected_path}"
        )
        # TODO: implement API call and byte comparison here.
        # Placeholder assertion confirms the fixture file is valid.
        assert expected_bytes, f"Fixture file has no content: {expected_path.name}"


# ---------------------------------------------------------------------------
# CSV byte-fidelity tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("municipality", MUNICIPALITIES)
def test_csv_byte_fidelity(municipality: str) -> None:
    """Compare API-generated CSV bytes against desktop-generated reference files.

    SKIPPED when no .csv reference fixtures are present for the municipality.

    TODO (once fixtures arrive):
        1. Parse emp_cod and vigencia from the reference filename
           (convention: relatorio_{emp_cod}_{vigencia}.csv).
        2. POST the XML files from input/ to the API.
        3. Poll GET /jobs/{id}/status until status == "completed".
        4. GET /jobs/{id}/download/csv  →  download_bytes
        5. Assert download_bytes == expected_path.read_bytes()
           (validates UTF-8-BOM encoding, semicolon delimiter, column order)
    """
    if not _has_expected_csv(municipality):
        pytest.skip(f"No reference CSV fixtures for '{municipality}' — add files to "
                    f"tests/fixtures/{municipality}/expected/ to enable this test")

    expected_files = _expected_csv_files(municipality)
    assert len(expected_files) > 0, (
        f"Expected CSV fixtures found but list is empty for '{municipality}'"
    )

    for expected_path in expected_files:
        expected_bytes = expected_path.read_bytes()
        assert len(expected_bytes) > 0, (
            f"Reference fixture is empty: {expected_path}"
        )
        # TODO: implement API call and byte comparison here.
        # Placeholder assertion confirms the fixture file is valid.
        assert expected_bytes, f"Fixture file has no content: {expected_path.name}"
